
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun May 15 22:04:59 CEST 2022
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int IGUALCOMP = 14;
  public static final int POR = 6;
  public static final int RET = 25;
  public static final int T = 33;
  public static final int PCIERRE = 11;
  public static final int LAP = 20;
  public static final int PUNTOCOMA = 18;
  public static final int ARRAY = 37;
  public static final int FOR = 29;
  public static final int F = 34;
  public static final int B = 36;
  public static final int AND = 21;
  public static final int IGUAL = 8;
  public static final int OR = 22;
  public static final int DIV = 7;
  public static final int TYPEDEF = 3;
  public static final int IF = 16;
  public static final int DIST = 15;
  public static final int EOF = 0;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int CORAP = 40;
  public static final int ASP = 39;
  public static final int COMA = 9;
  public static final int LCI = 19;
  public static final int MENOS = 5;
  public static final int MENOR = 13;
  public static final int VOID = 38;
  public static final int MAYOR = 12;
  public static final int ENT = 31;
  public static final int PAP = 10;
  public static final int ELSE = 23;
  public static final int PUNTO = 30;
  public static final int READ = 27;
  public static final int IDEN = 32;
  public static final int WHILE = 17;
  public static final int INT_0 = 35;
  public static final int DEF = 24;
  public static final int STRUCT = 4;
  public static final int CORCI = 41;
  public static final int PRINT = 26;
  public static final int MAS = 2;
}

