
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun May 15 00:40:16 CEST 2022
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int IGUALCOMP = 16;
  public static final int POR = 6;
  public static final int RET = 33;
  public static final int T = 24;
  public static final int PCIERRE = 11;
  public static final int LAP = 22;
  public static final int PUNTOCOMA = 20;
  public static final int ARRAY = 27;
  public static final int FOR = 40;
  public static final int F = 25;
  public static final int B = 23;
  public static final int AND = 28;
  public static final int IGUAL = 8;
  public static final int OR = 29;
  public static final int DIV = 7;
  public static final int TYPEDEF = 38;
  public static final int IF = 18;
  public static final int DIST = 17;
  public static final int EOF = 0;
  public static final int NEW = 39;
  public static final int error = 1;
  public static final int ASP = 36;
  public static final int CORAP = 12;
  public static final int COMA = 9;
  public static final int LCI = 21;
  public static final int MENOS = 5;
  public static final int MENOR = 15;
  public static final int VOID = 32;
  public static final int MAYOR = 14;
  public static final int ENT = 3;
  public static final int PAP = 10;
  public static final int ELSE = 30;
  public static final int PUNTO = 41;
  public static final int READ = 35;
  public static final int IDEN = 2;
  public static final int WHILE = 19;
  public static final int INT_0 = 26;
  public static final int DEF = 31;
  public static final int STRUCT = 37;
  public static final int CORCI = 13;
  public static final int PRINT = 34;
  public static final int MAS = 4;
}

